### ISSUE TITLE
Swift compile error "Use of undeclared type MTBBarcodeScanner"

### ISSUE THREAD

**Issue by chilion** [mikebuss/MTBBarcodeScanner#100]
Hi Mike (or anyone else that reads this)

I have an compile error, I guess I do something wrong, but I have no clue whatsoever what I would be doing wrong then.

![Code](https://puu.sh/tQMuZ/844dd9f31d.png)

**Comment by mikebuss** [comment]
You'll need to import the library:

```
import MTBBarcodeScanner
```

At the top, under `import UIKit`

**Comment by mikebuss** [comment]
Closing, but please comment or email me if you run into more issues.

**Comment by chilion** [comment]
Yeah this is actually something I already did;

![Screenshot](https://puu.sh/tQSqD/6e971da6c7.png)

**Comment by mikebuss** [comment]
How was MTBBarcodeScanner added to your project? It looks like it can't find the two source files (MTBBarcodeScanner.h and .m). Is this by any chance a project you can zip up and link here?

A few things off the top of my head:

- If you added the library through CocoaPods, make sure you're using the .xcworkspace and not the .xcodeproj file to open the project
- If you added through Carthage, you'll want to double check you followed all of the linking steps correctly, as that could cause this
- If you added manually, you may have to make sure they were added to the correct target

**Comment by mikebuss** [comment]
One more thing: if you added through CocoaPods, you'll need to use the flag:

```
use_frameworks!
```

At the top of your Podfile

**Comment by chilion** [comment]
![It already has](https://puu.sh/tQUkA/1b64222aa0.png <https://puu.sh/tQUkA/1b64222aa0.png>)

**Comment by mikebuss** [comment]
In that Podfile it looks like MTBBarcodeScanner is nested under the Tests target. Can you try moving it up to the main target, running a `pod install`, and seeing if that works?

**Comment by chilion** [comment]
See the new Podfile:
![Screenshot](https://puu.sh/tQVcJ/1cc90cc348.png)

Then I closed xCode and rebooted it, cleaned the project and I don't get any problems anymore. Next challenge for me is to open the scanner when I push a custom created button and get the input from the scanner into a textbox. 

Especially opening the scanner on button push is a challenge, do you have any hints for me in the right direction? 

Thanks so far and in advance!

**Comment by mikebuss** [comment]
The demo project does this, but it's in Objective-C. It should be straightforward to translate to Swift:

https://github.com/mikebuss/MTBBarcodeScanner/blob/develop/Project/MTBBarcodeScannerExample/Classes/Controllers/MTBBasicExampleViewController.m

**Comment by chilion** [comment]
I think I did make it happen in Swift, only problem here is that it won't actually open the camera. I did run through the debugger multiple times, it tells me it doesn't read any codes actually. But, it doesn't even open the camera! :)

Oh and yes, every time I hit that button, ejo is printed 

See my code:
![Code](https://puu.sh/tQY6e/333488187d.png)
