### ISSUE TITLE
Remove auto torch mode?

### ISSUE THREAD

**Issue by shagedorn** [mikebuss/MTBBarcodeScanner#110]
I think `MTBTorchModeAuto` doesn't work as expected, i.e., it doesn't work at all.

I've found an old radar that describes the issue:
http://www.openradar.me/15138815

Looking at the Camera app (in video mode), the behaviour is probably intentional: The torch doesn't turn on until you actually start a recording – while previewing, you only get an indicator (yellow box) that tells you if the app *would* use a torch.

I gave it a try if temporarily adding an `AVCaptureVideoDataOutput` output solved the problem – it does, but not without caveats:

* Startup time is slower, or if you toggle the torch mode when the session is active, there's a noticeable lag, which shouldn't happen for simply changing the torch mode
* "auto" only works at the start (i.e., when you add the output): if light conditions change later, the torch won't adapt
* Removing the output turns off the torch, so if you switch from "auto" to "on", but remove the output on a background queue (because of lags), the torch switches off. You can switch it on again, but then it will flicker.

I believe it would be best to remove/deprecate `MTBTorchModeAuto` entirely because it sets wrong expectations and is not something that seems easy to fix, unless you wanted to evaluate the video output yourself and decide when it's too dark to go without a torch.

**Comment by mikebuss** [comment]
Good catch. I originally created MTBTorchMode to map 1-to-1 with AVCaptureTorchMode so the user is given all the available options, but if Auto doesn't make sense from a barcode scanning perspective then it's definitely worth removing.

We can remove it entirely and release a v5.0.0 with the change. If users want to evaluate the raw video output and determine whether to turn on the torch dynamically, they're probably better off dropping down and using AVFoundation directly. MTBBarcodeScanner is more about the 80% case where people just want to start scanning.

**Comment by shagedorn** [comment]
Will remove then :)
