### ISSUE TITLE
Ambiguous reference to member 'startScanning()'

### ISSUE THREAD

**Issue by winzig** [mikebuss/MTBBarcodeScanner#112]
I've just upgraded from 3.x to 5.0, and I'm now receiving an error when I try to build my code. After a while of banging my head on the wall I decided to setup a sample project to simplify things and isolate the issue. So I'm using the same code in the README, and still getting the error:

<img width="734" alt="screen shot 2017-02-27 at 4 49 29 pm" src="https://cloud.githubusercontent.com/assets/127062/23386703/e2eb4270-fd0c-11e6-99a1-37be2eb07347.png">

Any ideas?

**Comment by winzig** [comment]
FWIW, I'm getting the same error with 4.0.

**Comment by mikebuss** [comment]
Hey @winzig, sorry you're running into this issue. I believe with the recent changes the function signature has changed to:

```swift
open func startScanning(resultBlock: (([AVMetadataMachineReadableCodeObject]?) -> Swift.Void)!) throws
```

When the change was made, the documentation wasn't updated to reflect the way Swift 3 requires you to call a method with this signature, which is:

```swift
do {
    try self.scanner?.startScanning(resultBlock: { codes in
        if let codes = codes {
            for code in codes {
                let stringValue = code.stringValue!
                print("Found code: \(stringValue)")
            }
        }
    })
} catch {
    NSLog("Unable to start scanning")
}
```

I have updated the [documentation](https://github.com/mikebuss/MTBBarcodeScanner/blob/develop/README.md) and added a [Swift example](https://github.com/mikebuss/MTBBarcodeScanner/blob/develop/Project/MTBBarcodeScannerExample/Classes/Controllers/SwiftExampleViewController.swift) to the demo project so any changes that break Swift 3.0 compatibility (or syntax) will get noticed quickly in the future.

Please let me know if this doesn't fix it on your end!

**Comment by jwmuchow** [comment]
Any chance you can include an Objective-C example using the new signature?
