### ISSUE TITLE
Preview View Wrong Size Initally

### ISSUE THREAD

**Issue by michaellatman** [mikebuss/MTBBarcodeScanner#114]
Hi there.

I have a preview view setup using constraints to fill the entirety of the users screen. I then spawn the view controllers and start scanning with MTBBarcodeScanner. The app starts scanning, but the preview view is initially too small. After a few moments it will expand to the correct size. No logs indicate any problems with the constraints, and the orange background color shows that the actual preview view is the proper size the entire time. 

Any ideas?

Thanks! 

Michael 
![Before](https://cloud.githubusercontent.com/assets/236019/23681716/00f4ca44-0388-11e7-9a2e-52dc683d1c61.PNG)
![After](https://cloud.githubusercontent.com/assets/236019/23681719/0390b380-0388-11e7-81f7-d1b5d47ad176.PNG)

**Comment by mikebuss** [comment]
Hey @michaellatman - are you calling `startScanningWithError:` from within `viewDidAppear` or `viewWillAppear`? You may try calling it from within `viewDidLayoutSubviews` if you're seeing this issue.

If that doesn't help, can you compare your project with the sample project in this repository? If you're able to reproduce it (or modify the example to reproduce it), it may help us debug the issue.

**Comment by michaellatman** [comment]
I was calling it within `viewDidAppear` moving it to `viewDidLayoutSubviews` worked.  

Thanks!

**Comment by mikebuss** [comment]
Cool. Happy scanning!

**Comment by shagedorn** [comment]
Just a note: I'm not sure if you should call `startScanning...` in `viewDidLayoutSubviews`, as this may be called many times (and will report errors in subsequent calls). Instead, I'd recommend only calling `setScanRect:` in `viewDidLayoutSubviews`.

**Comment by mikebuss** [comment]
That's a good point - I was assuming there was also a check to make sure you weren't already scanning.

Correct me if I'm wrong, but setting scanRect wouldn't update the camera feed size within the orange view above (which was the issue) - it would just update where barcodes are recognized from within the previewView. In general I wouldn't recommend calling startScanning from within viewDidLayoutSubviews, but it seems like something about this particular setup is making the normal call locations not work. 

I think I'd need to see the whole controller to know for sure what exactly was happening. 

Also one quick note: calling scanRect in viewDidLayoutSubviews might make sense in some setups, but you want to be extra careful that you've started scanning *beforehand* otherwise this call won't work. I think it's almost always a better call to set the scanRect inside the didStartScanning block. I'm sure everyone's mileage will vary, though.

**Comment by shagedorn** [comment]
True, sorry... I just glanced at it and concentrated at `startScanning`. There is a check for an active session, and if that triggers, we return `NO` and set the error parameter. It won't affect the running session and probably works, it just doesn't feel right, and you might be surprised to see the errors if you handle them.

In our app, we set `scanRect` in `viewDidLayoutSubviews` and within the `didStartScanning` block. If one of those is too early and fails (i.e., does nothing), it's not an issue.

**Comment by mikebuss** [comment]
I agree, calling it in `viewDidLayoutSubviews` doesn't feel right. You can make it a little more stomache-able by wrapping it in something like:

```objective-c
- (void)viewDidLayoutSubviews {
   if ([self.scanner isScanning] == NO) {
      // Start scanning
   }
}
```

But, that's not what I'd recommend, and I think a cleaner fix would be to find why the previewView isn't being laid out in this case. Using  `viewDidLayoutSubviews` was more of a debugging tactic, but ideally you'd call `startScanning` in `viewDidAppear` like in the example projects, and then call scanRect exactly like you're doing it.

**Comment by michaellatman** [comment]
Hey all,

I did do not think that `viewDidLayoutSubviews` is the correct place to put this code. I checked into the setScanRect and it seems to be about "where" you can scan qr codes in the image. 

I have constraints on the view for the preview view:
<img width="263" alt="screen shot 2017-03-08 at 5 13 22 pm" src="https://cloud.githubusercontent.com/assets/236019/23714903/c897b4ea-0422-11e7-96bd-b15284841b17.png">

Any ideas for that? The view itself is obviously the right size so i'm drawing a blank

**Comment by mikebuss** [comment]
Can you compare your project with the sample project in this repository? If you're able to reproduce it there, or make it more similar to your project and send that my way, it will be easier to debug.

**Comment by michaellatman** [comment]
It looks like `viewDidAppear` was the best place to put the scanning code, as suggested. It does make the app appear to be less responsive however as the view is transitioned modally and it will be orange for longer.
