### ISSUE TITLE
Scans when camera is not open

### ISSUE THREAD

**Issue by kmuddapu** [mikebuss/MTBBarcodeScanner#118]
Thanks for the Code !!

After the successful scan, I'm pushing from First Controller to Second Controller. But Camera continuously scans the QRCode when I place the phone on QRCode in Second controller without the camera open.

Can you please help me !!

**Comment by mikebuss** [comment]
I would suggest calling `stopScanning` before you push the second controller. That will ensure the session stops in the event the first controller isn't deallocated. 

Hope this helps! Feel free to comment if not.

**Comment by kmuddapu** [comment]
I did the same. but not working. 

Below is my flow. Correct me if I'm wrong 

1. Getting all View Controller in navigation stack  - Array[Zero Controller, First Controller]
2. Removing First Controller which has scanning Controller
3. Adding Second Controller to Stack

**Comment by mikebuss** [comment]
At what point in the flow are you calling `stopScanning`? You'll need to call it before step 2, I believe. To test that that's working, you might try NOT removing ZeroController and ensuring `stopScanning` is working, and then when you've confirmed it works try removing ZeroController.

If you're still getting callbacks of QR codes being scanned, it means the scanner object in ZeroController hasn't had the message `stopScanning` called to it. If you do this, you will not receive any more callbacks. Please see the demo project for an example of this.

**Comment by mikebuss** [comment]
Also, calling `stopScanning` in `viewWillDisappear` may not work here, depending on how you're swapping out view controllers. You will need to pass a message to the controller telling it to stop scanning before you swap it out.

**Comment by kmuddapu** [comment]
After successful scan. Calling **stopScanning** method as well as in **viewWillDisappear**. Then I'm removing the First Controller. 

Followed the same code from demo app.

I will check once again .
