### ISSUE TITLE
Orientation change not detected correctly

### ISSUE THREAD

**Issue by juliangoacher** [mikebuss/MTBBarcodeScanner#120]
I've found that the code at this line https://github.com/mikebuss/MTBBarcodeScanner/blob/develop/Classes/ios/Scanners/MTBBarcodeScanner.m#L436
```objective-c
UIInterfaceOrientation orientation = [UIApplication sharedApplication].statusBarOrientation;
```
doesn't detect orientation changes correctly, but changing the code to the following does work:
```objective-c
UIDeviceOrientation deviceOrientation = [UIDevice currentDevice].orientation;
...
- (AVCaptureVideoOrientation)captureOrientationForInterfaceOrientation:(UIDeviceOrientation)deviceOrientation {
switch (deviceOrientation) {
        case UIDeviceOrientationPortrait:
            return AVCaptureVideoOrientationPortrait;
        case UIDeviceOrientationPortraitUpsideDown:
            return AVCaptureVideoOrientationPortraitUpsideDown;
        case UIDeviceOrientationLandscapeLeft:
            return AVCaptureVideoOrientationLandscapeRight;
        case UIDeviceOrientationLandscapeRight:
            return AVCaptureVideoOrientationLandscapeLeft;
        default:
            return AVCaptureVideoOrientationPortrait;
        }
}
```

**Comment by mikebuss** [comment]
I will test this on my end and update the ticket. Under what circumstances are you seeing issues with the current method? I haven't seen any issues on my end, but our use cases may be different.

**Comment by mikebuss** [comment]
After some research, it looks like we may want to stick with `statusBarOrientation` as it takes into account the supported orientations for the app. Is it possible you were rotating the device to an orientation not supported by your app, and that's what was causing the issue?

**Comment by juliangoacher** [comment]
@mikebuss I don't think so. My setup is this - supported device orientations are:
```xml
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
```
The `MTBBarcodeScanner` class is init'd as:
```objective-c

        NSArray *codeTypes = @[ AVMetadataObjectTypeDataMatrixCode, AVMetadataObjectTypeQRCode ];
        _scanner = [[MTBBarcodeScanner alloc] initWithMetadataObjectTypes:codeTypes
                                                              previewView:_scannerPreview.preview];
```
(The preview property is an instance of `UIView`). The preview view is a full-screen view, I have the following to resize the preview after an orientation change:
```objective-c
- (void)viewWillTransitionToSize:(CGSize)size
       withTransitionCoordinator:(id <UIViewControllerTransitionCoordinator>)coordinator {
    [self.view setNeedsLayout];
    [self.view layoutSubviews];
    CGPoint origin = self.view.frame.origin;
    _scanner.previewLayer.frame = CGRectMake(origin.x, origin.y, size.width, size.height);
}
```
What I found in my testing is that `[UIApplication sharedApplication].statusBarOrientation` (when called via `UIDeviceOrientationDidChangeNotification`) was always reporting the *previous* device orientation *after* an orientation change, but that the correct orientation is reported with my changes.

**Comment by mikebuss** [comment]
I'll take a look at this. For your suggested method, it looks like [Apple's documentation](https://developer.apple.com/documentation/uikit/uidevice/1620053-orientation?preferredLanguage=occ) says the property will always return zero unless you first call 'beginGeneratingDeviceOrientationNotifications'. Did you find that to be the case in your testing? I didn't see that call in your example.

**Comment by juliangoacher** [comment]
Hmmm interesting - no, I'm not calling that method - and either is your code - so I'm not sure what's happening here.

**Comment by juliangoacher** [comment]
@mikebuss So I think I know what's happening, and how to fix it.

* I guess that [the call to start observing UIDeviceOrientationDidChangeNotifications](https://github.com/mikebuss/MTBBarcodeScanner/blob/develop/Classes/ios/Scanners/MTBBarcodeScanner.m#L582) must contain an implicit call to `beginGeneratingDeviceOrientationNotifications` - I can't find this behaviour documented anywhere, but I suppose it makes sense, and the fact is that the device orientation is reported correctly in my testing.
* The `UIDeviceOrientationDidChangeNotification` is explicitly tied to `UIDevice.orientation`, as you can see [in the documentation](https://developer.apple.com/documentation/uikit/uideviceorientationdidchangenotification). My guess here is that it's unspecified behaviour as to whether `UIApplication. statusBarOrientation` has been updated or not by the time the notification is fired. Certainly in my testing it wasn't updated at that point, and always reported the previous orientation value.
* However, the notification `UIApplicationDidChangeStatusBarOrientationNotification` is explicitly tied to updates of the `UIApplication.statusBarOrientation` property. If I reverse my suggested changes and instead change the code to observe `UIApplicationDidChangeStatusBarOrientationNotification` then everything works as expected.

I've made the change [in a forked copy of the repo](https://github.com/juliangoacher/MTBBarcodeScanner/commit/f742532095eb1e86cfc97613b17657f702d94ab7).

**Comment by mikebuss** [comment]
Good catch! Would you be able to submit a pull request with the changes from your fork? If so I can merge that in and we'll be good to go.

**Comment by mikebuss** [comment]
Fixed with https://github.com/mikebuss/MTBBarcodeScanner/pull/121. I will release a new version with this later tonight. Thanks!

**Comment by mikebuss** [comment]
This is now pushed in the 5.0.1 pod release. Thanks again!

**Comment by juliangoacher** [comment]
Great, glad to help!
