### ISSUE TITLE
Barcode not detected

### ISSUE THREAD

**Issue by Lukaz32** [mikebuss/MTBBarcodeScanner#124]
I'm trying to read the following barcode 
![barcode](https://user-images.githubusercontent.com/544727/28688652-f7776776-72e8-11e7-9b9b-6b97bc51bcf6.png)

but it's just never detected. I'm running the Basic Example.
Am I missing something or that type of barcode is not supported?

Thanks in advance

**Comment by mikebuss** [comment]
I'm not sure what type of code that is. Here is an official list of supported codes: 
https://developer.apple.com/documentation/avfoundation/avmetadatamachinereadablecodeobject/machine_readable_object_types

If it's not on that list, it won't be scannable by MTBBarcodeScanner. If you're able to scan other codes but not this one, and can't figure out what type of code this is, then it's most likely unsupported. Sorry!

**Comment by Lukaz32** [comment]
Thanks for the answer. The code is an [**interleaved2of5**](https://developer.apple.com/documentation/avfoundation/avmetadataobject.objecttype/1618825-interleaved2of5)
Apparently it should be supported :/

**Comment by mikebuss** [comment]
I've seen issues with older devices not having good enough cameras for larger or more intricate barcode types - what device are you using?

Can you also double check you're on the latest version of iOS and MTBBarcodeScanner? I believe this type isn't available to older versions of either, per this ticket: https://github.com/mikebuss/MTBBarcodeScanner/issues/15
