### ISSUE TITLE
Preview layer with incorrect size on iPhone 7+

### ISSUE THREAD

**Issue by treinberger** [mikebuss/MTBBarcodeScanner#125]
I encountered the following problem on a iPhone 7+ device: when I start scanning, the preview layer size is a little bit too small, but not on an iPhone 6. The constraints set for the preview UIView seem to be ignored. 

The way I temporarily fixed the problem is by manually setting the frame of the previewLayer as following:

scanner?.didStartScanningBlock = {() -> Void in
            self.scanner?.previewLayer.frame = self.scannerView.frame
        }

HTH someone :-)

**Comment by mikebuss** [comment]
Thanks! I will close this but it will still get indexed by Google for anyone who needs it.
