### ISSUE TITLE
setter for rectOfIntrest blocking

### ISSUE THREAD

**Issue by alistra** [mikebuss/MTBBarcodeScanner#128]
Hello, I've found another issue with blocking the main thread.

The method `-setScanRect` is setting the `rectOfIntrest` on the main queue, where occasionally it blocks. This happens to me often, when I try to turn the scanner off and on again many times.

According to apple sample this operation should be done on a session queue, not main queue.

https://developer.apple.com/library/content/samplecode/AVCamBarcode/Listings/AVCamBarcode_CameraViewController_swift.html

Screenshot where the blocking occurs
![screen shot 2017-08-17 at 11 38 18](https://user-images.githubusercontent.com/233144/29406389-36c3a4c2-8341-11e7-9469-910ebc0def12.jpg)

**Comment by mikebuss** [comment]
Ok, thanks for letting me know. I should have time to look at this over the weekend. Pull requests are also welcome.

**Comment by mikebuss** [comment]
I have a fix for this in bd8982b. Let me know if this fits your needs. I'm going to hold off on releasing this until next week so everyone has a chance to look over the changes. Thanks!

**Comment by alistra** [comment]
Works smooth like butter now! Okay to release for me.

**Comment by mikebuss** [comment]
This is now in 5.0.3. Thanks!
