### ISSUE TITLE
Add zoom feature for scanner

### ISSUE THREAD

**Issue by acuenco** [mikebuss/MTBBarcodeScanner#129]
Will a zoom feature be added to the scanner? If not, how can I approach supporting zoom for this library?

**Comment by mikebuss** [comment]
I have no plans to add zoom to MTBBarcodeScanner as it's not a commonly requested feature. To implement this, you will want to look at the AV Foundation documentation Apple provides:
https://developer.apple.com/av-foundation/

If you want to add what you implement back into MTBBarcodeScanner, please feel free to submit a pull request for review.

Thank you!
