### ISSUE TITLE
Type of codes?

### ISSUE THREAD

**Issue by doughboyks** [mikebuss/MTBBarcodeScanner#134]
I cannot get it to return BOTH barcodes.  This is an EAN13+5 barcode.

![image](https://user-images.githubusercontent.com/8210033/35464286-b9a6c768-02ba-11e8-9e0d-c83ff94bbe58.png)

**Comment by mikebuss** [comment]
Unfortunately, EAN13+5 is not supported by Apple's AVFoundation framework, so the full code can't be scanned by MTBBarcodeScanner. As you've experienced, only the EAN13 code can be scanned, not the other 5-digit code.

For a full list of codes, see this page:
https://developer.apple.com/documentation/avfoundation/avmetadatamachinereadablecodeobject/machine_readable_object_types?language=objc
