### ISSUE TITLE
There are warnings in Xcode 9 - is partial: introduced in iOS 10.0

### ISSUE THREAD

**Issue by LittlePeculiar** [mikebuss/MTBBarcodeScanner#135]
I haven't figured out how to fix these myself without changing the code so I thought I'd submit them as an issue. I'm running Xcode 9 and target is 10.3
"is partial: introduced in iOS 10.0"

'AVCapturePhotoSettings'
'AVCaptureResolvedPhotoSettings'
AVCapturePhotoOutput'
'defaultDeviceWithDeviceType:mediaType:position:'
'AVCaptureDeviceTypeBuiltInWideAngleCamera'
'JPEGPhotoDataRepresentationForJPEGSampleBuffer:previewPhotoSampleBuffer:'

**Comment by mikebuss** [comment]
Thanks for letting me know. I will take a look at this as soon as I can. I don’t believe this will negatively impact the library in the meantime.

**Comment by mikebuss** [comment]
@LittlePeculiar can you elaborate on where you're seeing this in the app? Does this warning appear in the demo project for you? I tried changing the target to iOS 10.3 in Xcode 9.2 but didn't see any of these warnings.

I'm going to close this for now but please feel free to update the issue.

**Comment by mikebuss** [comment]
I found it! This should be fixed in 900ea36, which will be part of the next release. Thank you!
