### ISSUE TITLE
Torch mode

### ISSUE THREAD

**Issue by armandsLa** [mikebuss/MTBBarcodeScanner#136]
Torch flickers and gets turned off automatically when setting torch mode to `.on`

I've found [issue](https://github.com/mikebuss/MTBBarcodeScanner/issues/54) which describes the same problem, but suggested fix did not help. I also tried to turn on torch from `didStartScanningBlock`, but that didn't help.

Dispatching witch 0.5sec delay from `didStartScanningBlock` worked, but I'm not sure how reliable this is.

**Comment by mikebuss** [comment]
Unfortunately it looks like the AVFoundation will toggle the torch when you initialize the components necessary for scanning barcodes (like the AVCaptureSesson). I will dig into possible solutions for this, but it may be that starting the torch after a short delay is your best bet. 

If you have time, I would definitely suggest filing a radar to Apple that AVFoundation shouldn't toggle the torch - that seems like an issue to me!

I will update this ticket if I find anything. I may have time next week to look into this. Pull requests are also welcome if you have a solution or suggestion. Thank you!

**Comment by armandsLa** [comment]
Thanks for the clarification. I was using version `5.0.3`, latest from cocoapods.  Updated to `5.0.4` but that didn't affect anything.

I will try to look more into this and submit a pull request if I manage to come up with something.

**Comment by mikebuss** [comment]
I'm going to close this as it's a problem with the underlying AVFoundation framework. I would definitely suggest filing a radar with Apple that starting a scanning session shouldn't flicker the torch. In the meantime, the delay seems like a fine (albeit annoying) workaround.
