### ISSUE TITLE
MTBBarcodeScanner.m Line : 878 Warning iOS 11.0

### ISSUE THREAD

**Issue by bykrkc** [mikebuss/MTBBarcodeScanner#137]
![image](https://user-images.githubusercontent.com/16520480/36865325-42cf92f4-1da0-11e8-9b79-6d5705967407.png)

How can I solve this problem?
Can you help me? Thanks.

**Comment by mikebuss** [comment]
This should be fixed in 900ea36, which will be in the next release. Thank you!
