### ISSUE TITLE
Getting 20 errors with the MTBBarcodeScanner class

### ISSUE THREAD

**Issue by lfarah** [mikebuss/MTBBarcodeScanner#14]
![screen shot 2014-12-28 at 12 39 48 am](https://cloud.githubusercontent.com/assets/6511079/5563468/170c534a-8e2a-11e4-8429-087e5e610535.png)

**Comment by mikebuss** [comment]
@lfarah I believe I found the solution to this. If you haven't already, you need to add the following import statement to MTBBarcodeScanner.m, or copy in the latest version from the `develop` branch:

`#import <UIKit/UIKit.h>`
