### ISSUE TITLE
Only works with iOS10+ after recent changes

### ISSUE THREAD

**Issue by nyisztor** [mikebuss/MTBBarcodeScanner#140]
Hi,
After pulling to the latest changes I received a lot of warnings like this:
> 'AVCaptureDeviceTypeBuiltInWideAngleCamera' is only available on iOS 10.0 or newer
This is a problem since we're still using older iPads that only support iOS 9.

I also understand if you don't plan to support older iOS versions. 
But then, please refresh project's description to show that only iOS10+ are supported.

**Comment by mikebuss** [comment]
Hi @nyisztor. Have you been able to test this on a device running iOS 9? I don't believe the warnings will be an issue, but I don't have an iOS 9 device.

**Comment by mikebuss** [comment]
I am going to close this but if someone notices issues with the library running on a physical device running iOS 9 please let me know.
