### ISSUE TITLE
Impossible to read CODABAR barcode

### ISSUE THREAD

**Issue by janky** [mikebuss/MTBBarcodeScanner#141]
Hello, i'm having trouble reading CODABAR Barcode (also known as USD-4, NW-7, 2 of 7, Ames and Monarch)

They aren't recognized by the library

you can try with this site https://www.free-barcode-generator.net/codabar/

**Comment by mikebuss** [comment]
This library can only scan codes from this list, as it's built on top of Apple's AVFoundation library:

https://developer.apple.com/documentation/avfoundation/avmetadatamachinereadablecodeobject/machine_readable_object_types
