### ISSUE TITLE
Initial camera setting

### ISSUE THREAD

**Issue by bompf** [mikebuss/MTBBarcodeScanner#143]
Hello,

am I right in saying that the scanner does not currently allow to specify which camera position is to be used after initialization? The `camera` property is set to readonly and exposed setters only work after initial setup has been done. If you switch the camera after setup (using `didStartScanningBlock`), you'll get a noticable flicker of the screen. 

The class initializers don't set the backing ivar directly, which means it's initialized with `0` mapping to enum case `MTBCameraBack`.

My suggestion would be to add a convenience initializer which lets you specify the initial camera position and sets the backing ivar appropriately.

**Comment by mikebuss** [comment]
Hey @bompf. You are correct: there is no way to set the camera property before scanning. This isn't high on my priority list, but if you'd like to submit a pull request adding this I can take a look.
