### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by BadChoice** [mikebuss/MTBBarcodeScanner#144]
Hi!
There are 13 warnings in the last xcode version,
I can fix them and create a PR, will you merge it and update the pod? or shouldn't I bother...

Thanks!

**Comment by BadChoice** [comment]
Thank you! that's amazing, as I did some in other projects, and they never said anything 

Will do it today/tomorrow

Thanks!

**Comment by BadChoice** [comment]
Actually, there is just one warning in the project, when in pod I get warnings of things not available before ios 10

Gonna send the PR for that one

**Comment by mikebuss** [comment]
This is in pod version 5.0.6 now. Thanks!
