### ISSUE TITLE
Can't read an interleaved 2 of 5 code

### ISSUE THREAD

**Issue by hdoria** [mikebuss/MTBBarcodeScanner#15]
I am using MTBBarcodeScanner for reading ITF barcodes, but it doesn't read correctly Brazilian Bills with 47 digits.

A sample PDF (for printing) is available here (https://drive.google.com/file/d/0ByQMtFUGwDRBWnZObkFBcDR1RVk/edit?usp=sharing) . The barcode sequence number is on the top of the bill (a long sequence of numbers separeted by point and space).

**Comment by mikebuss** [comment]
Hey @hdoria - thanks for bringing this to my attention. I just added support for this in 87692b3, and will release a new pod version later tonight.

Testing it with your barcode seems to work, but let me know if you encounter any issues with version 1.3.0.

![img_4214](https://cloud.githubusercontent.com/assets/1574304/5750250/0f36601c-9c20-11e4-9b49-9bc0589589cf.PNG)

**Comment by hdoria** [comment]
Awesome! Thank you.
