### ISSUE TITLE
Maximum of read multiple codes

### ISSUE THREAD

**Issue by Chris533** [mikebuss/MTBBarcodeScanner#153]
Hello Mike, could you tell me please whether reading multiple codes can only support 4 codes at most? I have tested it and can scan up to 4 pieces of qr codes at the same time, thanks a lot!

**Comment by Chris533** [comment]
[Apple FAQ: There is a limit of four barcodes per call](https://developer.apple.com/library/archive/technotes/tn2325/_index.html#//apple_ref/doc/uid/DTS40013824-CH1-CAN_AVCAPTUREMETADATAOUTPUT_DETECT_MULTIPLE_2_DIMENSIONAL_BARCODES_IN_A_FRAME_)
[Stackoverflow: detect more than four (4) QR codes](https://stackoverflow.com/questions/19431661/avcapturemetadataoutput-detect-more-than-four-4-qr-codes)

That seems to be the reason

**Comment by mikebuss** [comment]
Hi @Chris533. Apologies for the slow reply. You’re right: there’s a limit of 4 QR codes at a time. This is a limitation of Apple’s framework.

**Comment by Chris533** [comment]
That's OK, thanks for the code you created, thanks for your reply, ❤️ I will research other methods.
