### ISSUE TITLE
Problem configurating scanner with QR and Barcode

### ISSUE THREAD

**Issue by ayoze** [mikebuss/MTBBarcodeScanner#154]
Hello,

I am using this library since years to read lottery tickets barcode (Code128 = AVMetadataObjectTypeCode128Code). It worked since the beginning.
Now, in the same project we are supporting QR codes, so I just added the AVMetadataObjectTypeQRCode to the metadata object types when initializing
`self.scanner = [[MTBBarcodeScanner alloc] initWithMetadataObjectTypes:@[AVMetadataObjectTypeCode128Code, AVMetadataObjectTypeQRCode] previewView:self.scanView];`

The problem is that if I do that only the QR code is available for scanning, The barcode is completely ignored. 
When I noticed that, I just tried to remove the QR metadata type and I just worked again, so it seems the problem is there.

I've put a breakpoint inside the library, in the delegate method and it is never called in the case the 2 options are configured and I try to scan a Code128. It stops correctly with the QR.

Has anybody else viewed this behavior before?

Many thanks!

PS: just to add more info, I attach an example of the code.

![18_OCTUBRE_](https://user-images.githubusercontent.com/1452175/65794525-9be78300-e168-11e9-9824-a9dbf8d72a75.jpg)

**Comment by mikebuss** [comment]
Hi @ayoze. I tried this and I see what you mean. Can you try something? I was able to get the 128 code you attached to scan if I printed it out, or if I blow it up very large on the screen. It seems to be a bit blurry, which makes it harder to scan.

Adding the QR code type slows down the scanning considerably, especially with the image you linked. So, you may have to hold the camera over the image for much longer than you previously would. But, by enlarging the image (or viewing it printed out and not on a screen), I was able to get this to work with the following initializer:

```objective-c
_scanner = [[MTBBarcodeScanner alloc] initWithMetadataObjectTypes:@[AVMetadataObjectTypeQRCode, AVMetadataObjectTypeCode128Code] 
previewView:_previewView];
```

Hope this helps!

**Comment by ayoze** [comment]
Hello mike,

thanks for the quick answer. Ok, I'll check in an original (on paper) ticket and let you know as soon as posible. Thanks!

**Comment by mikebuss** [comment]
I am going to close this issue but if you encounter the problem again please feel free to comment on this ticket. I was able to scan the image above when I printed it out and waited longer than a second or two with the camera pointed at it.

**Comment by ayoze** [comment]
Sorry for the late reply Mike. I was doing some tests this last week. I followed your instructions and improved the scan time by using the scan rect property to a small rectangle. It works perfectly now.

Many thanks!

**Comment by mikebuss** [comment]
No problem, glad to hear it worked out!
