### ISSUE TITLE
output becomes Garbled text

### ISSUE THREAD

**Issue by awesomedu** [mikebuss/MTBBarcodeScanner#155]
when I use it to scan, but the output becomes Garbled text, the result is 201909290018$150602008001GB00058F00050005$ÃÉ(2019)¶õ¶û¶àË¹ÊÐ²»¶¯²úÖ¤Ã÷µÚ0008710ｺﾅ, I can I turn the words to right?, thanks very mush.

**Comment by mikebuss** [comment]
Can you share the QR or barcode you're trying to scan? Thank you.

**Comment by awesomedu** [comment]
![11111111](https://user-images.githubusercontent.com/28338863/67773848-58e63b80-fa97-11e9-85c9-4fcf1b91e466.jpeg)
this is the QRcode,many thanks for ur reply .

**Comment by awesomedu** [comment]
I reply u in the mail tool, the QRcode is in the mailbox attachment.many thanks for you repayment






发自我的iPhone


------------------ Original ------------------

**Comment by mikebuss** [comment]
Thank you. What is the QR code supposed to say? Can you try creating a new QR code using a website like this? https://www.qr-code-generator.com

**Comment by awesomedu** [comment]
![2222222222](https://user-images.githubusercontent.com/28338863/67775474-fb072300-fa99-11e9-8826-561e9f4211d9.png)
this is the new QRcode, the right words are in it .

**Comment by mikebuss** [comment]
I think the issue may be the quality of the original QR code. There seem to be lines going through it that may impact the text. You might try printing out a new QR code to see if that works. 

![Screen Shot 2019-10-29 at 10 31 10 AM](https://user-images.githubusercontent.com/1574304/67776899-6075f800-fa37-11e9-8978-60dda7bf056f.png)

**Comment by awesomedu** [comment]
I view the MTBBarcodeScanner's code , the core code is the AVFoundation's call back "- (void)captureOutput:(AVCaptureOutput *)output didOutputMetadataObjects:(NSArray<__kindof AVMetadataObject *> *)metadataObjects fromConnection:(AVCaptureConnection *)connection", 
metadataObject.stringValue is outputstring, problems occured here,  the first pic QRcode seems originally created with GBK encoding , if get the value by the 'metadataObject.stringValue' ,it causes the problem .first QRcode provided can scan out the right words with application 'wechat' , you can download one in appstore. Thank you very much for your reply.

**Comment by mikebuss** [comment]
Because the issue is happening inside of AVFoundation (in the callback you mentioned), I don't think there's anything this library can do to fix the issue. It seems to be happening before the code is returned to MTBBarcodeScanner. In that case, I would recommend filing a radar with Apple: https://feedbackassistant.apple.com

**Comment by awesomedu** [comment]
NSString *scanOutStr = @"201909290018$150602008001GB00058F00050005$ÃÉ(2019)¶õ¶û¶àË¹ÊÐ²»¶¯²úÖ¤Ã÷µÚ0008710ｺﾅ";
    NSString *cutLastTwoCharacterStr = @"201909290018$150602008001GB00058F00050005$ÃÉ(2019)¶õ¶û¶àË¹ÊÐ²»¶¯²úÖ¤Ã÷µÚ0008710";
    NSString *result = cutLastTwoCharacterStr;//返回的扫描结果
    NSData *data=[cutLastTwoCharacterStr dataUsingEncoding:NSUTF8StringEncoding];
    NSStringEncoding enc = CFStringConvertEncodingToNSStringEncoding(kCFStringEncodingGB_18030_2000);
    NSString *retStr = [[NSString alloc] initWithData:data encoding:enc];
    if (retStr)
    {
        NSInteger max = [cutLastTwoCharacterStr length];
        char *nbytes = (char *)malloc(max+1);
        for (int i = 0; i < max; i++)
        {
            unichar ch = [cutLastTwoCharacterStr characterAtIndex:i];
            nbytes[i] = (char)ch;
        }
        nbytes[max] = '\0';
        result=[NSString stringWithCString: nbytes encoding: enc];
        NSLog(@"result = %@",result);
    }

I tried like above, if cut the last words "ｺﾅ", it can get most of right words, if add them, it returns nil.
I think there're some ways to solove the encoding problem, I find many ways ,but still can't get whole right words. 

many thanks . Good night~~~~
