### ISSUE TITLE
when barcode data increased it is difficult to read Code..

### ISSUE THREAD

**Issue by AmeerChand** [mikebuss/MTBBarcodeScanner#157]
When we increase the length of barcode, it is very difficult to read the bar code from MTBarcodeScanner..
i.e **003** is easy to reader but if we change this like **000000000000000000000000003** then scanner say good bye...

**Comment by mikebuss** [comment]
The performance of MTBBarcodeScanner is linked to Apple’s AVFoundation framework. For issues like this, I would recommend filing a radar with them. Unfortunately, there’s not much I can do to improve scanning for complicated or long barcodes.
