### ISSUE TITLE
Define Barcodetype in Swift

### ISSUE THREAD

**Issue by bawesto** [mikebuss/MTBBarcodeScanner#159]
Usually restricting the scan to a certain Barcodetype is increasing the Performance.
So I'd like to do that, in my case QR-Code.

It's dokumented for Objective-C Projects in Readme, but I could not figure out how to do that in a Swift3+ Project. Can't find any dokumentation or example.
Is it possible? Could you provide a snipped how to do that?

Many thanks!

**Comment by ghost** [comment]
You should be able to initialize it with the same initializer as Objective C.
```swift
let scanner = MTBBarcodeScanner(metadataObjectTypes: [AVMetadataObject.ObjectType.qr.rawValue], previewView: someView)
```

**Comment by mikebuss** [comment]
@kmwillia's answer is correct. I will add more Swift examples to the README sometime over the weekend. Thanks for the suggestion @bawesto!

**Comment by mikebuss** [comment]
I added some examples to the project for this:
https://github.com/mikebuss/MTBBarcodeScanner/commit/e1c89a47ecf8d392b5fc89e27da221c9fb0e0b38

Thank you @bawesto for the suggestion and @kmwillia for the answer!
