### ISSUE TITLE
Camera Unfreeze method not working on.

### ISSUE THREAD

**Issue by KrupaVachhani** [mikebuss/MTBBarcodeScanner#160]
Hello there,

After scanning the barcode I set the camera to Freeze cause scanning works too quickly but after some actions, I want to unFreeze that camera. But It Freezes the screen.

**Comment by mikebuss** [comment]
Are you able to reproduce this issue in the demo project included with this repository? That will help us narrow down if it's something with the library or your code base.

One alternative to freezing the screen would be to only process a barcode if the last barcode was scanned longer than X seconds ago. This will work unless you need to show the screen freezing in the UI.

I will try to reproduce this on my end as well.

**Comment by mikebuss** [comment]
@KrupaVachhani I haven't been able to reproduce this. Please let me know if you are able to reproduce this in the demo project, or if the above suggestion helps.

I am going to close this for now, but please add more details if you can.

**Comment by KrupaVachhani** [comment]
It is solved now. I found another way and that solved my issue.
Thanks for your quick response. :)

**Comment by KrupaVachhani** [comment]
@mikebuss, It is solved now. I found another way from your demo app project and that solved my issue.
Thanks for your quick response. :)
