### ISSUE TITLE
Use library in swift

### ISSUE THREAD

**Issue by sumitjain7** [mikebuss/MTBBarcodeScanner#18]
How Would I use this library in swift?

**Comment by mikebuss** [comment]
Hey @sumitjain7 - I don't have any Swift examples in the example project right now, but here's a quick sample that compiles.

I will add a Swift example to the official example as soon as I can.

```swift

class MTBSwiftExampleViewController: UIViewController {

    var scanner: MTBBarcodeScanner
    @IBOutlet var previewView: UIView?
    
    required init(coder aDecoder: NSCoder) {
        scanner = MTBBarcodeScanner(previewView: previewView)
        super.init(coder: aDecoder)
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        
    }
    
    override func viewDidAppear(animated: Bool) {
        super.viewDidAppear(animated)
    
        scanner.startScanningWithResultBlock { (var codes) -> Void in
            for code in codes {
                // Output all of the codes just scanned
            }
        }
        
    }

}


```

**Comment by mikebuss** [comment]
Closing this for now. If you have any trouble, please feel free to contact me [directly](mailto:mike@mikebuss.com) so we can keep the issue system only for issues.

**Comment by sp-wisebits** [comment]
> so we can keep the issue system only for issues
lack of documentation could be viewed as an issue, right? 😉

**Comment by mikebuss** [comment]
> lack of documentation could be viewed as an issue, right?

This library was built for Objective-C projects - if you'd like to submit documentation for how to use it in Swift, I would happily accept pull requests. In the meantime, the above code is a great start.
