### ISSUE TITLE
Unable to Build the Example Project

### ISSUE THREAD

**Issue by coala2000** [mikebuss/MTBBarcodeScanner#19]
Hi, I am unable to build the example project. I am getting this error:
```objective-c
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```

Here is a screenshot of the error:
![screen shot 2015-03-13 at 4 43 27 pm](https://cloud.githubusercontent.com/assets/4240128/6647780/187cd11c-c9a0-11e4-8d62-170dd947ba5e.png)

I just downloaded the zip of the current GitHub code and tried to build and run the example project. I tried installing cocoapods and running through some of the steps in these stackoverflow posts, http://stackoverflow.com/questions/17072396/cocoapods-errors-on-project-build. I get an error when I try to run ```pod install```, here is the error: ```[!] No `Podfile' found in the project directory.```

Thanks for your time.

**Comment by haydenzone** [comment]
Having the same issue

**Comment by mikebuss** [comment]
@coala2000 and @haydenzone, can you try again with the latest change I just pushed?

It looks like the test target had a few CocoaPods-related build phases, even though the sample project doesn't require CocoaPods. Something changed with Xcode 6.2 that made these pop up even when you're not building the test target. I removed them, and it looks OK now. Please let me know if you're still encountering any issues!

**Comment by coala2000** [comment]
Thanks for all the help, that seems to have fixed my error.
