### ISSUE TITLE
Cannot recognize Data Matrix codes when using the front camera

### ISSUE THREAD

**Issue by adamgall** [mikebuss/MTBBarcodeScanner#22]
Data Matrix codes are not recognized when using the front camera. They are, however, recognized if the Data Matrix code is inverted (either using an image manipulation program such as Photoshop, OR when the code is read through a mirror... which took some dexterity to pull off). I suspect this is due to some image-flipping closer to the hardware, and the fact that Data Matrix codes have an orientation.

Might this bug exist in your library, or shall I submit a radar with Apple?

**Comment by adamgall** [comment]
After looking through this library's source, it seems apparent that the bug is with Apple's AVCaptureMetadataOutput implementation. I'll close this. Thanks for your easy to use library!

**Comment by mikebuss** [comment]
Thanks for bringing this to my attention. If anything changes with `AVCaptureMetadataOutput` I'll be sure to incorporate the fix into this library as well.

P.S. I've worked with DXY Solutions before - keep up the great work!
