### ISSUE TITLE
help

### ISSUE THREAD

**Issue by guizmo** [mikebuss/MTBBarcodeScanner#23]
Hi Mike,
I don't know much about objectiv C but i work a lot with cordova and i wanted to ask if you had an idea on how to port your scanner to cordova.... I tried but i failed like a noob ;)

**Comment by mikebuss** [comment]
Hey @guizmo - sorry, I don't have any experience with Cordova and can't be much help here.

You may try this library:
https://github.com/xocialize/XocializeScanner/

Best of luck!
