### ISSUE TITLE
Focus issue

### ISSUE THREAD

**Issue by sebastianludwig** [mikebuss/MTBBarcodeScanner#25]
I've got an app that uses `MTBBarcodeScanner` and an `UIImagePickerController` and ran into a few auto focus issues. Please see my [focus_bug_demo branch](https://github.com/sebastianludwig/MTBBarcodeScanner/tree/focus_bug_demo) for an illustration.

For all cases you need to restart the app to reproduce the effects.

1. Opening the barcode scanner first, the camera focuses on near and far objects equally good
1. Opening the barcode scanner two times yields the same behavior
1. Opening the image picker first, the camera focuses on near and far objects equally good
1. Opening the image picker two times yields the same behavior
1. Opening the barcode scanner first and then the image picker, the camera will only focus on near objects
1. Opening the barcode scanner, then the image picker and the barcode scanner again, the camera will only focus on near objects

Everything is consistent on my iPad Air and iPad 4. 

It seems to me that line 335 in `MTBBarcodeScanner.m` 

```
newCaptureDevice.autoFocusRangeRestriction = AVCaptureAutoFocusRangeRestrictionNear;
```

is not applied properly for the current session but seems to persist for the `UIImagePickerSession`. Removing the line results in the last two scenarios performing like to the ones above. However, I'm guessing the end of the last scenario is actually the desired behavior of line 335, is it?

I'm not even sure this is a `MTBBarcodeScanner` issue or rather an iOS bug, but since we can't fix iOS `MTBBarcodeScanner` should work around the issue.

Maybe changing the `autoFocusRangeRestriction` back to `AVCaptureAutoFocusRangeRestrictionNone` in `stopScanning` is an option?

**Comment by mikebuss** [comment]
Thanks for bringing this to my attention. That's a really odd bug.

> Maybe changing the autoFocusRangeRestriction back to AVCaptureAutoFocusRangeRestrictionNone in stopScanning is an option?

We can definitely do this. Have you found this fixes the issue? Would you mind testing this on your branch, and maybe submitting a pull request with the one-line change? If you don't have time, let me know and I can try later this week.

If we made this change, how would the library handle crashing while scanning? Would the `autoFocusRangeRestriction` be stuck on `AVCaptureAutoFocusRangeRestrictionNear`? 

It seems odd to me that `UIImagePickerController` isn't configuring the `AVCaptureDevice` returned from `defaultDeviceWithMediaType:` before capturing video. I'm sure Apple knows others will be configuring the device, and there's no documentation saying we need to revert our changes, so this might be worthy of filing a radar.

**Comment by sebastianludwig** [comment]
Nope, not fixed.

The `currentCaptureDeviceInput` reference is only set in `setCamera` which is not called during the initial setup through `newSessionWithCaptureDevice`. The other way round the focus range and focus point are not set then switching cameras because that code is only in `newCaptureDeviceWithCamera` and not in `setCamera`. That's why I had the `setDeviceInput:session:` in my PR to do both and had that called from `newSessionWithCaptureDevice` and `setCamera`.

**Comment by mikebuss** [comment]
Good catch. I just pushed a change under version 1.6.1 that should be a lot closer to your initial implementation. Can you give this a try and let me know if this fixes the issue?

Sorry for the back and forth. I'm having a hard time reproducing on my iPhone 6+ or iPad Air (1 and 2).

**Comment by sebastianludwig** [comment]
Again, I already left work so I'm without test devices, but I had a co-worker test it and he confirmed your fix :+1:

**Comment by mikebuss** [comment]
Great - thanks for all the help!
