### ISSUE TITLE
Weird issue with wrong orientation at startup

### ISSUE THREAD

**Issue by winzig** [mikebuss/MTBBarcodeScanner#28]
For some reason, the scanner's video view does not completely fill the layer that I supply, there's about a centimeter (on my iPhone 6) on one edge of the screen that's just black. When I debug it, though, my view is definitely filling the entire screen. But for some reason, the video layer isn't.

At the same time, the orientation of the video itself is wrong (and sort of looks zoomed in). So if I'm holding the phone in landscape, the video is like I'm looking at the top or bottom half of a PORTRAIT-oriented video view. So if I start panning, instead of the video moving side-to-side, it's moving vertically. Very strange. 

My guess is I'm doing something wrong, because when I first started integrating MTBBarcodeScanner, it wasn't doing this. But I've been working on it all day and can't figure out what's wrong. So I thought I'd check and see if the symptoms I'm describing are obvious to anyone? :-)

**Comment by winzig** [comment]
Oh, forgot the other part of this. Once I re-orient the device at all, the video preview layer fixes itself: video is oriented the right way, and the black area goes away!

**Comment by mikebuss** [comment]
Hey @winzig - can you share what version of iOS you're using? Are you able to reproduce this issue using the demo project on your phone?

If you have a demo project you could send my way, or if you could modify the MTBBarcodeScanner demo project to produce the same results, that would help.

I haven't seen this on my end yet, but I'll continue trying to reproduce.

**Comment by winzig** [comment]
Hi @mikebuss, thanks for responding. I thought for sure this was going to be a weird thing specific to my implementation, but luckily I was able to create a simple demo showing the problem. I'm running this on an iPhone 6. In this demo, I simplified it by not forcing the barcode scanner view to be landscape mode, so the behavior is slightly different than described above, but the same basic problems remain:

1. There's a gap at the bottom edge of the view
2. The camera appears to be zoomed in, in addition to being cut off.

If you rotate the device in any direction, the problem goes away.

https://github.com/winzig/BarcodeTest

**Comment by mikebuss** [comment]
Thanks for providing the demo project - that was super helpful in debugging this. 

I believe the issue is related to how the view is drawn on the screen. It looks like the `previewView` isn't drawn properly if the MTBBarcodeScanner starts scanning in `viewDidLoad`. On my device, if you wait a few seconds for the view to redraw, the bar eliminates itself, but what we really want is for the bar never to appear.

If you move the code from `viewDidLoad` to `viewDidAppear`, the gap at the bottom edge of the view never appears and everything seems to work as intended. I'll look to see if there's a way to start scanning earlier in the view lifecycle, but for now I think this is your best bet.

Please let me know if that fixes the issue on your end as well!

**Comment by mikebuss** [comment]
> The camera appears to be zoomed in, in addition to being cut off.

Forgot to address this. MTBBarcodeScanner sets the camera focal point of interest to be the center of the image, so you'll see a little zooming. The library doesn't currently support a way to set the [videoZoomFactor](https://developer.apple.com/library/ios/documentation/AVFoundation/Reference/AVCaptureDevice_Class/#//apple_ref/occ/instp/AVCaptureDevice/videoZoomFactor) property on the AVCaptureDevice, but I may add that in future versions. Let me know if that's something that would help you and I'll try to fit it in!

**Comment by winzig** [comment]
This fixed the issue, thanks!
