### ISSUE TITLE
[Qustion]is it possible to freeze the view once the qrcode reading is successful?

### ISSUE THREAD

**Issue by franklingu** [mikebuss/MTBBarcodeScanner#30]

**Comment by mikebuss** [comment]
There's no way to do this using MTBBarcodeScanner alone. 

I would suggest taking a screenshot using [UIGraphicsGetImageFromCurrentContext](http://stackoverflow.com/questions/7915370/ios-how-to-capture-a-particular-portion-of-screen), put the resulting UIImage in a UIImageView beneath the `previewView`, stop the scanner, and then remove the `previewView` from it's superview. This will make the camera input appear to have frozen on the screen.

**Comment by mikebuss** [comment]
Hey @franklingu - support for this has now been added to the library thanks to @felipowsky. The scanner object now has `freezeCapture` and `unfreezeCapture` methods. Hope this helps!
