### ISSUE TITLE
MTBBarcodescanner and iPhone 6

### ISSUE THREAD

**Issue by mangochot** [mikebuss/MTBBarcodeScanner#32]
Hi Mike, 

I'm using your scanner in one of my apps, and it is working great for iphone 4s and 5. However, many users of the app are complaining about it not working well on iphone 6. I have tried it on iPhone 6, and my experience is that sometimes it works fine, and sometimes it does not react to the barcode at all.

Do you recognize the problem?
Do you have any recommended fixes or things I might try out to make it work better on iPhone6?

It works really well on iphone 4s, so it is making me very confused that it is not working properly on iphone 6.

Best,

Kasper

**Comment by mikebuss** [comment]
Hey Kasper - MTBBarcodeScanner is built on top of Apple's AVFoundation, so it should work with all devices. 

Are you scanning with the front or back camera? In some cases, the front camera has too low of a resolution to scan the barcode accurately. This is usually on iPads, though.

You may try dropping down a level and implementing the AVFoundation scanning directly. The [MTBBarcodeScanner.m](https://github.com/mikebuss/MTBBarcodeScanner/blob/develop/Classes/ios/Scanners/MTBBarcodeScanner.m) file will give you a good idea on how to do this. If the problem still exists there, you may try tweaking some settings (`autoFocusRangeRestriction`, `focusPointOfInterest`, etc) and seeing if that improves the situation. If you do encounter settings that work better, please report back so I can incorporate them into this library.

If AVFoundation doesn't work, you'll want to submit a [bug report](https://bugreport.apple.com/) to Apple detailing the steps you took.

I only have an iPhone 5, 5S, and 6+ to test with, but I haven't seen this issue on any of them. Could you send over the barcodes you're using, as well as information about which camera?

Thanks!

**Comment by mangochot** [comment]
I have now tried something that seems too simple but does work. Could it really be that the solution is to place the barcode a bit below the center of the iphone's screen? I thought the iphone could scan the barcode no matter where it was placed on the camera view.

**Comment by mikebuss** [comment]
Yes it should work anywhere on the screen. You may try using AVFoundation directly and seeing if the problem persists. Or tweaking the settings in your local copy of MTBBarcodeScanner.m

**Comment by mikebuss** [comment]
I was able to try this on a few iPhone 6's and haven't seen the issue. If you have a way to reproduce this, please let me know and I will reopen!
