### ISSUE TITLE
- (BOOL) hasTorch;

### ISSUE THREAD

**Issue by jaybowong** [mikebuss/MTBBarcodeScanner#37]
```
// .h
/// Return a BOOL value that specifies whether the current capture device has a torch
- (BOOL) hasTorch;

// .m
- (BOOL) hasTorch {
    return self.currentCaptureDeviceInput.device.hasTorch;
}
```
I think it's necessary to add this method. 
Or make the current capture device a readonly property.

A torch toggle button should not be shown on an iPad and this method is needed to hide the torch toggle button.

**Comment by felipowsky** [comment]
Good call! I've created a [pull request](https://github.com/mikebuss/MTBBarcodeScanner/pull/40) for this.

**Comment by mikebuss** [comment]
Added by @felipowsky [here](https://github.com/mikebuss/MTBBarcodeScanner/pull/40). Thanks for the awesome work guys!

One caveat: `hasTorch` will currently only work when MTBBarcodeScanner is scanning. Please let me know if this is an issue and we can readjust.
