### ISSUE TITLE
Switch Camera permission in Settings makes crash the app

### ISSUE THREAD

**Issue by popei69** [mikebuss/MTBBarcodeScanner#42]
When I try to use the example code with basic view controller and I switch Camera permission in Settings app, it makes crash the app.

**Comment by mikebuss** [comment]
When you deny access to the Camera in the Settings app to an app, iOS will force-close the app. This is expected. If you relaunch the app, you should see the following alert if access is denied:

![img_3091](https://cloud.githubusercontent.com/assets/1574304/9659929/0932b97e-5221-11e5-8919-779b46e09fde.PNG)

**Comment by popei69** [comment]
Thanks for this quick answer. Yes I also noticed that it crashes when switching to accepting after denied it. 
I was wondering if there is any chance to avoid crash / kill the app on that.

Thanks,

**Comment by mikebuss** [comment]
Unfortunately I don't think there's a way around this, as it's done at the OS level. Sorry!
