### ISSUE TITLE
Get notified when camera starts scanning.

### ISSUE THREAD

**Issue by jaybowong** [mikebuss/MTBBarcodeScanner#43]
![2](https://cloud.githubusercontent.com/assets/1948533/9955720/de7642e4-5e25-11e5-91a6-85c441d2139b.png)
---
`startScanningWithResultBlock` takes a while to get camera ready to use especially when it comes to a full screen preview view. I want to show a preparing indicator UIActivityIndicatorView before call `startScanningWithResultBlock` and get notified when the camera is ready and shown to use so I can stop animating that indicator. This user experience is better if there's a loading indicator while waiting.

The following lines of code is just preparing the camera but it takes enough time to make users wait.
```objc
    if (!self.hasExistingSession) {
        AVCaptureDevice *captureDevice = [self newCaptureDeviceWithCamera:self.camera];
        self.session = [self newSessionWithCaptureDevice:captureDevice];
        self.hasExistingSession = YES;
    }
    
    [self.session startRunning];
```

Instruments shows this.
![3](https://cloud.githubusercontent.com/assets/1948533/9956022/e378490c-5e27-11e5-94c7-99f831a2fcf6.png)
I don't know how to translate that **22.0ms** CPU time into real time but it indeed made me wait.

--
Since there's no delegate in MTBBarcodeScanner, I'm thinking about adding a block property in the header file.
`@property (nonatomic, copy) void (^didStartScanningBlock)();`
And call this block in MTBBarcodeScanner like below.
```objc
- (void)startScanningWithResultBlock:(void (^)(NSArray *codes))resultBlock {
    // ...
    
    [self.session startRunning];
    // ...

    // Last three line
    if (self.didStartScanningBlock) {
        self.didStartScanningBlock();
    }
}
```

----
What do you guys think?

**Comment by mikebuss** [comment]
Sounds like a great idea! If you have some time to add this, please feel free. If not, I may be able to spend some time next weekend on this feature.

**Comment by mikebuss** [comment]
@jaybowong I found some time to implement this. This should be in 1.8.3, which I just released.

Please let me know if there are any other changes I could make that will be useful. Thank you!

**Comment by mikebuss** [comment]
For reference, this was the exact change I made. It fits your suggestion: https://github.com/mikebuss/MTBBarcodeScanner/commit/0bd3f4c71c32ee5d3a6ce55a72e5f0fea07766c2

**Comment by jaybowong** [comment]
@mikebuss You're so fast! I'm so happy that I just wake up and saw this.
I didn't send a pull request first because I think it's better to discuss first for this one.

Awesome! 👍
