### ISSUE TITLE
Scanner does not scan unless the scanRect is set explicitly (iOS 9 13A344)

### ISSUE THREAD

**Issue by okipol88** [mikebuss/MTBBarcodeScanner#46]
Hi, 

The Scanner has beeen working marvelousely for me.
Unfortunately on iOS 9 if you don't set the `scanRect` property it fails to deliver scan results.

This is easily reproducable in the basic example. It simply does not scan. The advanced example on the other hand scans without a flaw. When i set the `scanRect` in the basic example it starts working again.

**Comment by peterpaulis** [comment]
+1

**Comment by mikebuss** [comment]
Looks like this is a bug that slipped in with version 1.8.4. Sorry about that. Can you guys try version 1.8.5 on iOS 9 and see if the issue persists?

**Comment by peterpaulis** [comment]
Thanks, looks ok now
