### ISSUE TITLE
Add 'tap to focus' functionality

### ISSUE THREAD

**Issue by nickw444** [mikebuss/MTBBarcodeScanner#47]
Since there is no ability to access the internals of the scanner (AVCaptureSession, AVCaptureDevice), it is technically impossible to extend the library to add tap to focus. 

Is there any scope for getters and setters for the AVCaptureSession and AVCaptureDevice to be made public? 

Cheers

**Comment by mikebuss** [comment]
Hey @nickw444, thanks for the suggestion. I can definitely add tap-to-focus functionality to MTBBarcodeScanner, but I don't have any plans to expose the capture session or device. 

I'm hoping to keep the library as easy to use as possible, which means abstracting some of these details away from the user and exposing easier interfaces. For example with the torch functionality, we almost chose to expose the `AVCaptureDeviceInput` object, which would make turning on the torch as simple as:

```objective-c
if ([captureDeviceInput.device hasTorch]) {
    if ([captureDeviceInput.device lockForConfiguration:nil] == YES) {
        [captureDeviceInput.device setTorchMode:AVCaptureTorchModeOn];
        [captureDeviceInput.device unlockForConfiguration];
    }
}
```

But instead we exposed a simpler way, which is now:

```objective-c
self.scanner.torchMode = MTBTorchModeOn;
```

This takes away some of the functionality (i.e. we can't tell if the device actually *has* a torch), but for the majority of use-cases that's OK.

If you think adding tap-to-focus would be useful, I can maybe add a `tapToFocus` boolean to the library to enable this. Were you thinking of implementing this in a way similar to this?:

- User taps the `previewView`
- Based on the tap location, the `focusPointOfInterest` is set to a window around the touch

Or were there other properties you wanted to change based on user interaction?

Pull requests are also welcome if you'd like to implement this. I should be able to get to it in the next few weeks, but some people have tight deadlines and choose to take a swing themselves!

**Comment by nickw444** [comment]
Hey @mikebuss that's a fair reason for hiding the internals. Simple is better! 

Implementing touch to focus similar to how the torch is implemented is a great way to go about it - no need for the user to rely on their own implementation. I like it!

I can only see a single issue with this - user feedback. It would be nice to show the user where they touched, and, not every app will do this the same - they might want to use different UI Features, or just not show the user at all.

My suggestion is that upon touch handle, a block/callback is triggered, which allows the user to provide their own feedback view drawing code, which will paint the feedback square (or whatever view they wish) over the preview view. (and at the same time MTBBarcodeScanner handles the focusing)

This would allow MTBBarcodeScanner to handle the internals of focusing, whilst still allowing the user to provide their own custom UI. 

What are your thoughts on this method? 

I'll see if I can find some time to implement this (since it would improve 2 apps using this library), however i'm also pretty tied up at the moment.

**Comment by mikebuss** [comment]
Yes that sounds great.

**Comment by jaybowong** [comment]
Want this feature so much!

**Comment by jaybowong** [comment]
@nickw444 Have you implemented this? How about a PR?  I think a lot of people need this feature and it can help a lot.

It's quite often to me that It doesn't focus when scanning a bar code (e.g. a bar code on the back of a book).

**Comment by mikebuss** [comment]
@jaybowong I can take a stab at this over the weekend. I will update this ticket with the results.

**Comment by mikebuss** [comment]
I added an initial implementation for this. When the user taps the screen, MTBBarcodeScanner will now set the `focusPointOfInterest` to the point the user tapped, and call a block named `didTapToFocusBlock()`, which can be overridden for custom drawing.

The full details can be found [here](https://github.com/mikebuss/MTBBarcodeScanner/commit/9a04e623005f7744806a997e0f386e8a420ba66c). The README also has documentation on this.

Please feel free to submit a PR with any improvements.

**Comment by jaybowong** [comment]
Thanks @mikebuss  👍
Can't wait to try this!

**Comment by nickw444** [comment]
Awesome stuff. I'll be sharing a gist as soon as I can which uses this and adds a apple camera like focus square.
