### ISSUE TITLE
DataMatrix not identified next to edges when using scanRect 

### ISSUE THREAD

**Issue by nickw444** [mikebuss/MTBBarcodeScanner#48]
There seems to be a slight issue with DataMatrix codes and using a scanRect.

Steps to reproduce:
 - Open advanced demo
 - Place scanner over DataMatrix code. Align code on the right (or left) side of the scan rect.
 - No code detected - Expected result: code detected
 - Slowly move device to align code to the centre of the scan rect. Code is detected.
 - Slowly move device to align code back to the right (or left) side. Code is detected in some places where it was not before, but does not stay detected all the way to the edge. 

Perform the above steps with a QR Code, and see that it is detected no matter where it is positioned in the scan rect. 

I am not sure if this is an issue with this library or an issue in Apple's implementation of QR decoding. 

### Screenshots of DataMatrix:
![screen shot 2015-09-25 at 3 32 55 pm](https://cloud.githubusercontent.com/assets/1289759/10093823/99063626-639b-11e5-98e5-2c2c7f7af675.png)
![screen shot 2015-09-25 at 3 33 03 pm](https://cloud.githubusercontent.com/assets/1289759/10093824/9bcfe5e6-639b-11e5-8e15-1ef840fd10f7.png)
![screen shot 2015-09-25 at 3 33 01 pm](https://cloud.githubusercontent.com/assets/1289759/10093827/a659831e-639b-11e5-8258-765a6c07cb9a.png)
![screen shot 2015-09-25 at 3 33 01 pm](https://cloud.githubusercontent.com/assets/1289759/10093832/b286a662-639b-11e5-9d68-eab5a02895eb.png)

### Screenshots of QR Code (Expected Behaviour)
![screen shot 2015-09-25 at 3 33 26 pm](https://cloud.githubusercontent.com/assets/1289759/10093840/c2411f42-639b-11e5-95ec-07b155efd5fb.png)
![screen shot 2015-09-25 at 3 33 28 pm](https://cloud.githubusercontent.com/assets/1289759/10093845/cc04a652-639b-11e5-9ef9-7febb32c6273.png)

**Comment by mikebuss** [comment]
MTBBarcodeScanner doesn't make a distinction between a QR code scanRect and a DataMatrix scanRect, so I'm pretty sure this is an issue with AVFoundation. You may want to create a sample project with straight AVFoundation code and send it to Apple in a [radar](https://developer.apple.com/bug-reporting/). If you find that the pure AVFoundation sample project doesn't have this issue, please let me know and we can investigate any differences.
