### ISSUE TITLE
i can't scanner the qrcode.

### ISSUE THREAD

**Issue by jacksonpan** [mikebuss/MTBBarcodeScanner#5]
![236a8ab929274a530f4a8cf492984d4f](https://cloud.githubusercontent.com/assets/696493/3455088/4f5d270a-01db-11e4-9c48-0ecaa2422759.jpg)
hi, i can't scanner the qrcode.
can you fix it?
and tell me why?
thanks

**Comment by amoshsueh** [comment]
@jacksonpan Did you find any solution for unprintable characters? I have the same situation, wanna get some help if you are available. Thanks in advanced.
