### ISSUE TITLE
Add "recognize from picture" functionality

### ISSUE THREAD

**Issue by peterpaulis** [mikebuss/MTBBarcodeScanner#50]
We have a large QR, which is quite problematic to recognise with using video, however, from a single photo it could be recognised better

there could be a functionality for taking a picture and than analysing it

**Comment by peterpaulis** [comment]
<code>
I have captured image while scanning QRCode like this:

1) Firstly add property of AVCaptureStillImageOutput's

@property (strong, nonatomic) AVCaptureStillImageOutput *stillImageOutput;
2) Add session preset in AVCaptureSession after initializing it

[self.session setSessionPreset:AVCaptureSessionPreset640x480];
3) Now add AVCaptureStillImageOutput's as output in AVCaptureSession

// Prepare an output for snapshotting
self.stillImageOutput = [AVCaptureStillImageOutput new];
[self.session addOutput:self.stillImageOutput];
self.stillImageOutput.outputSettings = @{AVVideoCodecKey: AVVideoCodecJPEG};
4) Make add below code to capture scanned image in delegate method captureOutput:didOutputMetadataObjects:fromConnection:connection

 __block UIImage *scannedImg = nil;
// Take an image of the face and pass to CoreImage for detection
AVCaptureConnection *stillConnection = [self.stillImageOutput connectionWithMediaType:AVMediaTypeVideo];
[self.stillImageOutput captureStillImageAsynchronouslyFromConnection:stillConnection completionHandler:^(CMSampleBufferRef imageDataSampleBuffer, NSError *error) {
    if(error) {
        NSLog(@"There was a problem");
        return;
    }

    NSData *jpegData = [AVCaptureStillImageOutput jpegStillImageNSDataRepresentation:imageDataSampleBuffer];

    scannedImg = [UIImage imageWithData:jpegData];
    NSLog(@"scannedImg : %@",scannedImg);
}];
For reference use CodeScanViewController
</code>

**Comment by peterpaulis** [comment]
http://stackoverflow.com/questions/20782584/avfoundation-avcapturemetadataoutput-capturing-screenshoot

**Comment by peterpaulis** [comment]
i have been able to achieve this, however i had use zbar, maybe a function, for taking a photo with a block callback would be sufficient

**Comment by mikebuss** [comment]
I like this idea, but I'm hoping to avoid adding ZBar as a dependency to MTBBarcodeScanner just for this feature. If we can find a way to do this with AVFoundation, I think that's our best bet for keeping the library lightweight and bug-free.

In the meantime you may have to use ZBar in combination with MTBBarcodeScanner to accomplish this. At least until the feature is added to AVFoundation.

**Comment by peterpaulis** [comment]
i have been playing with

<code>
        CIDetector* detector = [CIDetector detectorOfType:CIDetectorTypeQRCode context:nil options:@{CIDetectorAccuracy:CIDetectorAccuracyHigh}];
        if (detector)
        {

            NSArray* featuresR = [detector featuresInImage:scannedImg.CIImage];
            NSString* decodeR;
            for (CIQRCodeFeature* featureR in featuresR)
            {

                NSLog(@"decode %@ ",featureR.messageString);
                decodeR = featureR.messageString;

            }

        }
</code>

but it didnt gave results like ZBar

**Comment by mikebuss** [comment]
That could work. I'll take a look at that API and see if there's something I can do. Thanks for the info!

**Comment by mikebuss** [comment]
In an effort to keep GitHub Issues for bugs and issues, I'm moving this to the [Suggested Features](https://github.com/mikebuss/MTBBarcodeScanner/blob/develop/Documentation/SuggestedFeatures.md) document.

Please submit a pull request if you'd like to tackle this one.
