### ISSUE TITLE
setScanRect, scanning stops working after orientation change

### ISSUE THREAD

**Issue by peterpaulis** [mikebuss/MTBBarcodeScanner#53]
I'am setting the scanRect, but after orientation change and setting it again with the adjusted coordinates, the scanning stops working

**Comment by mikebuss** [comment]
Thanks for bringing this to my attention. I was able to reproduce this on my end and implement a fix in version 1.8.7, which is now pushed. 

With the new changes, you should be able to update the `scanRect` when the orientation changes similar to the [new code in the example project](https://github.com/mikebuss/MTBBarcodeScanner/commit/b57bb1402a8ae2b9b2202507e43739407da48d08). Please let me know if you encounter any more issues here.

**Comment by yudiz-mahavir** [comment]
scanRect is not detecting QR Code after changing orientation in iPhone X, I've same code as [example project](https://github.com/mikebuss/MTBBarcodeScanner/commit/b57bb1402a8ae2b9b2202507e43739407da48d08)

Also your demo project is also crashing in iPhone X (`AdvancedExampleVC`)
