### ISSUE TITLE
Light (torch) flickers when turning on using torchMode

### ISSUE THREAD

**Issue by winzig** [mikebuss/MTBBarcodeScanner#54]
If I set torchMode to MTBTorchMode.On before I start scanning, the light turns on briefly, then turns off, then turns back on (i.e. it flickers as it comes on). 

If I instead put it in a code block that is delayed by 100 ms so that the code runs AFTER the scanning has started, then it does not flicker on, it just comes on solid (albeit delayed slightly). 

I'm assuming this may be related to this PR: https://github.com/mikebuss/MTBBarcodeScanner/pull/36

But it's not clear to me exactly what is going wrong. Is anyone else seeing this behavior?

**Comment by mikebuss** [comment]
Thanks for bringing this to my attention. I was able to replicate this on my end as well.

This looks to be an issue with AVFoundation - I can't seem to start scanning without flickering the torch if it was already on. I was however able to update the library to allow you to set the torchMode to ON *after* you start scanning. So, the following code will now avoid the flicker without using a delay:

```objective-c
[self.scanner startScanningWithResultBlock:^(NSArray *codes) {
    ...
}];
    
self.scanner.torchMode = MTBTorchModeOn;
```

This is now live in version 1.8.8. Please let me know if you encounter any issues on your end.

**Comment by winzig** [comment]
Awesome, thanks @mikebuss, works great!
