### ISSUE TITLE
Crash on iOS7

### ISSUE THREAD

**Issue by ztepsa** [mikebuss/MTBBarcodeScanner#55]
MTBBarcodeScanner.m
`self.stillImageOutput.highResolutionStillImageOutputEnabled = YES;`
should be 
`        if ([self.stillImageOutput respondsToSelector:@selector(isHighResolutionStillImageOutputEnabled)]) {
            self.stillImageOutput.highResolutionStillImageOutputEnabled = YES;
        }`

**Comment by mikebuss** [comment]
Thank you for bringing this to my attention. This should now be fixed in version 1.8.9.

Please let me know if you encounter any other issues on iOS 7 - unfortunately I only have iOS 8 and 9 devices to test with at the moment.
