### ISSUE TITLE
<Error>: CGAffineTransformInvert: singular matrix. in Swift

### ISSUE THREAD

**Issue by hardikdevios** [mikebuss/MTBBarcodeScanner#65]
I am having this error everytime i restart the Scaning and its stops working for capturing the Barcode.

```
func scanningStart(){
        
        self.scanner.startScanningWithResultBlock { (codes) -> Void in
            self.scanner.stopScanning()           
            // Doing my task here and after that 
             self.scanner.startScanning()
         })

        }
        scanner.scanRect = viewIntrest.frame

  }

```

**Comment by mikebuss** [comment]
Hey @hardikdevios - can you check if the `viewIntrest.frame` value is zero? If this is the case, MTBBarcodeScanner won't be able to properly frame the scan rect.

If it's not, can you set a breakpoint in `setScanRect:` in MTBBarcodeScanner.m and see what the value of `self.captureOutput.rectOfInterest` is after the assignment? If this is zero, it's possible your `viewIntrest.frame` isn't within the `previewView` you supplied in `initWithPreviewView:`.

**Comment by hardikdevios** [comment]
@mikebuss Thanks boss solved issue it was an Autolayout issue in Landscape mode cheers .
