### ISSUE TITLE
IPAD ISSUE

### ISSUE THREAD

**Issue by soufianeEssabbane** [mikebuss/MTBBarcodeScanner#67]
Hi mike, thanks for the great work you're doing. I use MTBBarcodeScanner in an universal app, it works like a charm in iPhone but not in iPad sometimes it works sometimes no ...
thanks

**Comment by mikebuss** [comment]
Hi @soufianeEssabbane - can you provide more details here? Are you seeing a crash? If so, can you produce a stack trace?

The camera on the iPad isn't quite as good as some iPhones, so that may be your issue.

**Comment by soufianeEssabbane** [comment]
Hi @mikebuss  thanks for the replay, I actually use the same code you're using in the sample (:$) I have an iPad Air and it just doesn't detect the qrcode sometimes. you need to try many times before it works it's kind of random behavior ... and the same code works super fine in iPhone devices ... it shows no error. the problem is that i'm not able to explain or give more details...
do you think that it may be a problem related iPad cams ?

![webportal](https://cloud.githubusercontent.com/assets/1910912/14563235/bf356926-0318-11e6-9dd8-cfd5cf352049.png)

**Comment by mikebuss** [comment]
Unfortunately the iPad camera isn't as high quality as the iPhone cameras. I think that is the issue you're seeing. I'm going to close this, as it sounds like a hardware issue. If you find a way to improve this, please let me know, but I think you're limited by the camera quality.

**Comment by soufianeEssabbane** [comment]
Thanks sir
