### ISSUE TITLE
Carthage Support

### ISSUE THREAD

**Issue by hardikdevios** [mikebuss/MTBBarcodeScanner#69]
It would be great if you give support for Carthage.

**Comment by mikebuss** [comment]
I'm not familiar enough with Carthage to add this. If someone would like to submit a pull request with this functionality, I would gladly merge it in.

**Comment by hardikdevios** [comment]
I can but you have to drop support for iOS 7 as Carthage only suppots from iOS 8

**Comment by mikebuss** [comment]
That's OK - we can do a major breaking v2.0.0 release. If anyone wants to keep support for iOS 7 they'll have to use v1.9.1 and CocoaPods. I will make sure this is noted in the documentation.

**Comment by hardikdevios** [comment]
Ok then i will make PR for that before sunday

**Comment by hardikdevios** [comment]
Not to much wait buddy here you go 
#70 
Merged it . I have Updated README.md also with Carthage Badge and instruction to install using Carthage.

**Comment by mikebuss** [comment]
This is now in v2.0.2. Thanks @hardikdevios!
