### ISSUE TITLE
[Bug] v1.9.1: captureOutput:didOutputMetadataObjects:fromConnection: crash on ios7

### ISSUE THREAD

**Issue by navicor90** [mikebuss/MTBBarcodeScanner#71]
I see high rate crash on `captureOutput:didOutputMetadataObjects:fromConnection:` in my crash report. I use 1.9.1 MTBBarcodeScanner with iOS 7 support. 

### _Stacktrace_

    n     |  file                |      selector
-----| ----------------------------------------- | ----------------
0	| myApp	 | [MTBBarcodeScanner captureOutput:didOutputMetadataObjects:fromConnection:] (in myApp) (MTBBarcodeScanner.m:367)
1	| AVFoundation	| +[AVOutputSettings outputSettingsWithOutputSettingsDictionary:] (in AVFoundation) + 69
2	| libdispatch.dylib | 	0x000000018e179833 (in libdispatch.dylib)
3	| libdispatch.dylib | 	0x000000018e17981f (in libdispatch.dylib)
4	| libdispatch.dylib | 	_Xwakeup_runloop_thread (in libdispatch.dylib) + 55
5	| CoreFoundation | 	__CFArrayCopyDescription (in CoreFoundation) + 445
6	| CoreFoundation | 	_CFSTFeatureCounterCreate (in CoreFoundation) + 105
7	| CoreFoundation | 	CFBasicHashGetCountOfKey (in CoreFoundation) + 2303
8	| CoreFoundation | 	CFBasicHashGetCountOfKey (in CoreFoundation) + 1763
9	| GraphicsServices | 	__Initialize_block_invoke (in GraphicsServices) + 1079
10	| UIKit |	-[UIImageView startAnimating] (in UIKit) + 473
11	| myApp |	main (in myApp) (main.m:17)
12	| libdyld.dylib |	0x000000018e195ab7 (in libdyld.dylib)

I analysed this exception, and I found that the method `captureOutput:didOutputMetadataObjects:fromConnection:` is called multiples times([As Apple documentation says](https://developer.apple.com/reference/avfoundation/avcapturemetadataoutputobjectsdelegate/1389481-captureoutput?language=objc)) even after that stopScanning was executed. Then resultBlock is `nil`.

**Comment by navicor90** [comment]
I've made the fix (diff is [here](https://github.com/mikebuss/MTBBarcodeScanner/compare/1.9.1...navicor90:fix-result-block-ios7)), but I think that you should create an `iOS7-support` branch to create the tag 1.9.2, because I started my fix in the tag 1.9.1.

**Comment by mikebuss** [comment]
Thank you for finding the fix @navicor90. I will create a pull request with your change, merge it into the main `develop` branch, release a v2.0.3 (iOS 8+), and then merge the change into a `iOS7-support` branch based off v1.9.1 for iOS 7 support. 

I'll update this ticket when this is all finished!

**Comment by mikebuss** [comment]
Ok, I created a branch called [`iOS7-support`](https://github.com/mikebuss/MTBBarcodeScanner/tree/iOS7-support) which is based off v1.9.1 for iOS 7 and has the above fix.

I've also released v2.0.3 with this fix, but that will require iOS 8+. Thanks again!

**Comment by navicor90** [comment]
can you release v1.9.2( with iOS7 support)? then I update my podfile. Thanks!

**Comment by mikebuss** [comment]
I'd prefer not to release a 1.9.2 if we're already officially at 2.0.3, but there is a way around this:

Can you point your Podfile at the `iOS7-support` branch, like so?

`pod "MTBBarcodeScanner", git: 'git@github.com:mikebuss/MTBBarcodeScanner.git', branch: 'iOS7-support'`

This will get you this fix, and also keep iOS 7 support, even though MTBBarcodeScanner has officially dropped this support in v2.0.0.

**Comment by navicor90** [comment]
@mikebuss we use podspec file, because we have a pod that wrap your library for many apps. And the podspec file does not allow set the github repo.
