### ISSUE TITLE
Bar code

### ISSUE THREAD

**Issue by Jkurbs** [mikebuss/MTBBarcodeScanner#73]
Hi Mike can it read this type of bar code? Thank you!
![barcode](https://cloud.githubusercontent.com/assets/10508898/16971286/7511c182-4df0-11e6-8dac-ee525f1ddb45.jpg)

**Comment by shekbagg** [comment]
What does it read it it as?

**Comment by mikebuss** [comment]
Yes, this will scan. In the future, there is a sample project provided with the repository that will allow you to test codes. Thanks!
