### ISSUE TITLE
Extra 0 when scan a UPC barcode

### ISSUE THREAD

**Issue by ASAPWebTeam** [mikebuss/MTBBarcodeScanner#76]
When we scans a UPC barcode, the iOS device adds an extra zero in front of the barcode number

**Comment by mikebuss** [comment]
Yes, this is expected of UPC-A codes. The AVFoundation framework adds a leading zero to the `stringValue`.

From Technical Note 2325:

> UPC-A is a formal subset of EAN-13. A decoded UPC-A barcode is output as AVMetadataObjectTypeEAN13Code with a leading zero in the stringValue.

https://developer.apple.com/library/ios/technotes/tn2325/_index.html
