### ISSUE TITLE
Aztec bar code not getting read

### ISSUE THREAD

**Issue by ravi-pixometry** [mikebuss/MTBBarcodeScanner#80]
Hello Sir,

Thanks for this amazing library. I am trying to scan Aztec qr code but i am not able to do that so i like to know that weather i can read the Aztec qr code using this library or not?

Thanks,

**Comment by mikebuss** [comment]
Hey there! You can find a list of supported barcodes here: https://developer.apple.com/library/ios/documentation/AVFoundation/Reference/AVMetadataMachineReadableCodeObject_Class/index.html#//apple_ref/doc/constant_group/Machine_Readable_Object_Types

I will also look into getting this into the README file. Thanks.
