### ISSUE TITLE
focusMode = AVCaptureFocusModeContinuousAutoFocus

### ISSUE THREAD

**Issue by JacopoKenzo** [mikebuss/MTBBarcodeScanner#81]
Hi,
I was playing around with the library and I found out that changing the focusMode to AutoFocus improves a lot the usability of the scanner.
Testing with iPhone 5 iOS 10 GM was really hard to focus on a QR code even if the `autoFocusRangeRestriction` is set to `AVCaptureAutoFocusRangeRestrictionNear`.

        // Focus on the center of the image
        if ([deviceInput.device respondsToSelector:@selector(isFocusPointOfInterestSupported)] &&
            deviceInput.device.isFocusPointOfInterestSupported) {
            
            self.initialFocusPoint = deviceInput.device.focusPointOfInterest;
            deviceInput.device.focusPointOfInterest = CGPointMake(kFocalPointOfInterestX, kFocalPointOfInterestY);
            deviceInput.device.focusMode = AVCaptureFocusModeContinuousAutoFocus;
        }

Cheers!

**Comment by mikebuss** [comment]
Thanks @JacopoKenzo - it looks like the focusMode is currently set to `AVCaptureFocusModeContinuousAutoFocus ` in the latest version ([line 338](https://github.com/mikebuss/MTBBarcodeScanner/blob/develop/Classes/ios/Scanners/MTBBarcodeScanner.m#L338)) of MTBBarcodeScanner. If you try the latest version, does this fix any focus issues on your end?

**Comment by JacopoKenzo** [comment]
@mikebuss yes i'm using the last version, `AVCaptureFocusModeContinuousAutoFocus` is set when the user tap-to-focus, not when the camera starts. That means an extra tap from the user.

And also tapping the camera didn't really focus on my end, that's why i set the AutoFocus property in the init of the camera, so the user doesn't have to tap.

**Comment by mikebuss** [comment]
Good catch - I've updated this in https://github.com/mikebuss/MTBBarcodeScanner/commit/e7a6f263e1259f360d251a40d4262b0fa5250042 and will push a new version out shortly. Thank you!

**Comment by mikebuss** [comment]
This is now in the pod version `2.1.0` if you'd like to update on your end. Thanks again!
