### ISSUE TITLE
Add more examples for Swift 3.0

### ISSUE THREAD

**Issue by ltlombardi** [mikebuss/MTBBarcodeScanner#90]
Using this lib in Swift 3 is a little bit trickier, because of all the optionals and `code` needs to be converted to `AnyObject` or `AVMetadataMachineReadableCodeObject` to the the `stringValue`. Here is the code I have to figure it out. Would be nice to put it on the readme.md. This is for "To continuously read and only output unique codes:":

`    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        MTBBarcodeScanner.requestCameraPermission { (success: Bool) in
            if success {
                self.scanner?.startScanning( resultBlock: self.scannerResult, error: nil)
            }
        }
    }
    
    func scannerResult (codes: [Any]?) {
        let codes = codes as! [AVMetadataMachineReadableCodeObject]?
        for code in codes! {
            let stringValue = code.stringValue!
            if self.uniqueCodes.index(of: stringValue) == nil {
                self.uniqueCodes.append(stringValue)
                print("Found unique code: \(stringValue)")
            }
        }
    }`

**Comment by mikebuss** [comment]
Thanks @ltlombardi - good idea. I've added a Swift 3 example based on your code to the README. [Here](https://github.com/mikebuss/MTBBarcodeScanner/commit/3697003c603f815dc88b461c8ff137160d9416be) is the commit.
