### ISSUE TITLE
Possible to add support for Digimarc Barcode

### ISSUE THREAD

**Issue by cspinelive** [mikebuss/MTBBarcodeScanner#91]
Digimarc has a new imperceptible barcode technology that covers entire packages with barcodes.  They have a paid SDK that can read them.  Do you think this is something that could be added to your SDK?  

https://www.digimarc.com/docs/default-source/discover-resources/brochures/dmrc-tech-overview-digimarc-barcode.pdf?sfvrsn=14

https://talkbusiness.net/2016/10/the-supply-side-wal-mart-testing-watermark-barcodes/

**Comment by mikebuss** [comment]
I don't have any plans to add paid SDK's to MTBBarcodeScanner, although if Apple adopts this in their AVFoundation framework I will make sure it is added. If anything changes, I will update this ticket. Thanks!

**Comment by mikebuss** [comment]
I should add: if anyone wants to submit a pull request with this functionality, I will gladly add it in. Until then, MTBBarcodeScanner will just support the codes that AVFoundation does.
