### ISSUE TITLE
Camera is scanning whole device screen, even if display a smaller frame

### ISSUE THREAD

**Issue by ltlombardi** [mikebuss/MTBBarcodeScanner#93]
I tested and realised that although i can create a scanner in a small UIView, let's say, half the size of the device screen, the rest of the camera feed is being scanned also, even if it's not shown to the user. 

I think I can use "Limiting the Scan Zone" to solve this problem, using the "previewView.frame", but it seems it should be the default behavior. Only scan the part of the camera feed that is been shown on the screen.

**Comment by mikebuss** [comment]
This may be something I implement in the future, but I think the more common case is the `previewView` takes up the entire screen, or most of the screen. Having MTBBarcodeScanner set the `scanRect` to the `previewView.frame` would be a solution, but what if that frame changes size? Is MTBBarcodeScanner then monitoring the `previewView` for frame changes?

Also, there may be a case where someone wants to show part of the preview but allow scanning from the entire range of the camera. That's also an edge case, but if you tie `previewView.frame` and `scanRect` together, this becomes much more difficult (or impossible).

If someone wants to submit a PR with a suggested implementation, I can take a look, but this seems like a very minor enhancement that comes with a bunch of "gotchas".

Thanks!
