### ISSUE TITLE
Add full Objective-C example (like Swift ones)

### ISSUE THREAD

**Issue by fmaylinch** [mikebuss/MTBBarcodeScanner#98]
First of all, thanks for this great scanner.

I just thought it would be good to add a full Objective-C example, the same way you add Swift examples. I'm saying this because I made a mistake and didn't call `startScanningWithResultBlock` in `viewDidAppear` but in `viewDidLoad`. The scanner seems to work anyway, but it responds slower.

Thanks!

**Comment by mikebuss** [comment]
Good idea. I added a note about using `viewDidAppear` instead of `viewDidLoad` to the README. I'll also look at adding a full Objective-C example - I would pull the code from the sample project, but it uses a button to initiate scanning.

Thanks!
